plugins:
  - uses:
      - plugin: "https://os-command-start-stop.ubq.fi"
        skipBotEvents: false
  - uses:
      - plugin: "https://os-command-demo.ubq.fi"
  - uses:
      - plugin: "https://os-command-wallet.ubq.fi"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@v1.2.0"
        with:
          model: "deepseek/deepseek-r1-0528:free"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
  - uses:
      - plugin: "https://os-command-query.ubq.fi"
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@v1.7.3"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator:
              openAi:
                endpoint: "https://openrouter.ai/api/v1"
                model: "deepseek/deepseek-chat-v3-0324:free"
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            payment: {}
            githubComment: {}
            reviewIncentivizer: {}
            simplificationIncentivizer: {}
            externalContent:
              llmImageModel:
                model: "meta-llama/llama-4-maverick:free"
              llmWebsiteModel:
                model: "deepseek/deepseek-chat-v3-0324:free"
          evmPrivateEncrypted: "oXan0e_gvkz6hjPKW_W6wjUDuUYwUKs77FQQiYmbH3XtYGfg8T2VzsFsrrcNnPm2YYM2nvdrT7ZeQJxMbfE0gu7qtp1TdE03k6n95iPk8B1qeR-a0gQuTL1T4zUIKNTHcques0F9acothZi-C8zzIgqFabtBb3BY4On9gvLynijplWAiDw"
          evmNetworkId: 100
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@v1.0.0"
  - uses:
      - plugin: "ubiquity-os-marketplace/text-vector-embeddings@v1.0.0"
        with:
          demoFlag: true
